### ISSUE TITLE
downloader needs to be aware of location of `programdata` for config (windows)

### ISSUE THREAD

**Issue by derekwbrown** [DataDog/integrations-core-downloader#1]
The current `tuf` config hard codes the location of the `repositories_dir` at build-time to to `c:\programdata\
Datadog\...`.  However, the directory might not be rooted at `c:\programdata`, and that must be determined at runtime.

Provide a mechanism where the config can be supplied a substitution variable that can be evaluated at runtime to fine the root of the programdata tree.

**Comment by trishankatdatadog** [comment]
Fixed with 6092ea55bbf9c0eedafdbe2a00c7aae06f4ca810
